import type { CareerChartOutline } from "../types/career-chart";

export const careerChartFallbackOutline: CareerChartOutline = {
  pageTitle: "Dream Route guider",
  pageSubtitle: "Your Complete Indian Career Hierarchy",
  note: "Explore education paths from 10th standard through postgraduate studies and professional growth.",
  sections: [
    {
      id: "level-1",
      sidebarLabel: "After 10th (S.S.C.)",
      title: "Level 1: After 10th Standard (S.S.C.)",
      description:
        "Choose your first major career branch after completing 10th standard. Options include technical trades, engineering diplomas, defense services, and skill courses.",
      bullets: [
        "- ITI (2-year skill-first technical trades for early employability)",
        "- Diploma Engineering (3-year polytechnic programs)",
        "- Police & Defense (Uniformed service tracks with government recruitment)",
        "- Skill Courses (6-12 month digital and vocational programs)",
      ],
    },
    {
      id: "level-2",
      sidebarLabel: "After 12th Standard",
      title: "Level 2: After 12th Standard (H.S.C.)",
      description:
        "After 12th, choose by stream: Science, Commerce, or Arts. Each stream leads to specialized bachelor's degrees and professional paths.",
      bullets: [
        "- 12th Science Stream",
        "    - Engineering Degree (JEE/CET based, 4 years)",
        "      - Computer Science / IT",
        "      - Mechanical Engineering",
        "      - Civil Engineering",
        "      - Electronics & Telecommunication",
        "      - AI & Data Science",
        "    - Medical & Life Sciences (4-5.5 years)",
        "      - MBBS (5.5 years)",
        "      - BDS (5 years)",
        "      - B.Pharm (4 years)",
        "      - B.Sc Nursing (4 years)",
        "    - Science & Computing (3 years)",
        "      - B.Sc Computer Science",
        "      - BCA",
        "      - B.Sc IT",
        "      - B.Sc Physics",
        "- 12th Commerce Stream",
        "    - Finance & Accounts (3-5 years)",
        "      - Chartered Accountancy",
        "      - Company Secretary",
        "      - B.Com",
        "      - B.Com in Finance / Management",
        "    - Management & Business (3-5 years)",
        "      - BBA",
        "      - BMS",
        "      - Digital Business",
        "      - Integrated BBA LLB",
        "- 12th Arts Stream",
        "    - Design & Media (3-4 years)",
        "      - UI / UX Design",
        "      - Journalism & Mass Media",
        "      - Fashion Design",
        "      - Fine Arts",
        "    - Public Service & Humanities (3+ years)",
        "      - B.A.",
        "      - Bachelor of Social Work",
        "      - Psychology",
        "      - Civil Services Foundation",
      ],
    },
    {
      id: "level-3",
      sidebarLabel: "Undergraduate & Professional Courses",
      title: "Level 3: Undergraduate & Professional Courses",
      description:
        "Bachelor's and professional degree programs (3-5.5 years) that combine theoretical knowledge with practical skills. Options span engineering, medicine, commerce, humanities, and design.",
      bullets: [
        "- Engineering Programs (4 years)",
        "    - Computer Science / IT: Software engineering, systems design",
        "    - Mechanical: Design, thermodynamics, manufacturing",
        "    - Civil: Infrastructure, construction, surveying",
        "    - Electronics & Telecom: Embedded systems, communications",
        "    - AI & Data Science: Machine learning, analytics",
        "- Medical & Health Sciences (4-5.5 years)",
        "    - MBBS: Doctor career pathway (5.5 years)",
        "    - BDS: Dental surgeon pathway (5 years)",
        "    - B.Pharm: Pharmacist and pharma roles (4 years)",
        "    - B.Sc Nursing: Registered nurse pathway (4 years)",
        "- Commerce & Business Programs (3 years)",
        "    - B.Com: Accounting and commerce foundations",
        "    - B.Com Finance / Management: Financial analysis",
        "    - BBA: Business management and operations",
        "    - BMS: Strategy and business systems",
        "- Computing & IT Programs (3 years)",
        "    - B.Sc Computer Science: Programming, data structures",
        "    - BCA: Applications and full-stack foundations",
        "    - B.Sc IT: Networking, software, support systems",
        "- Arts & Humanities Programs (3 years)",
        "    - B.A.: Humanities and social sciences",
        "    - Bachelor of Social Work: Community and development",
        "    - Psychology: Behavior and mental health studies",
        "- Design & Creative Programs (3-4 years)",
        "    - UI / UX Design: Research, interfaces, product design",
        "    - Journalism & Mass Media: News, writing, production",
        "    - Fashion Design: Apparel and styling",
        "    - Fine Arts: Visual arts and illustration",
      ],
    },
    {
      id: "level-4",
      sidebarLabel: "Postgraduate & Advanced Studies",
      title: "Level 4: Postgraduate & Career Outcomes",
      description:
        "Advanced specialization and leadership programs (1-2 years) for career growth, research, and executive roles after graduation.",
      bullets: [
        "- Postgraduate Technology & Engineering (1-2 years)",
        "    - MCA: Software engineering and applications (2 years)",
        "    - M.Tech in CS / AI: Advanced computing (2 years)",
        "    - PG in Data Science: Analytics and ML systems (1-2 years)",
        "    - PG in Cybersecurity: Security engineering (1-2 years)",
        "- Postgraduate Management & Leadership (1-2 years)",
        "    - MBA: Management, finance, leadership (2 years)",
        "    - PGDM: Industry-focused management (2 years)",
        "    - Marketing Analytics: Growth and campaigns (1-2 years)",
        "    - Product Management: Digital product strategy (1 year)",
        "- Research & Specialized Studies",
        "    - M.Sc in specializations: Physics, Chemistry, Biology, Computers",
        "    - Ph.D.: Science, engineering, and research pathways",
        "    - Diploma programs: Professional certifications and specialist skills",
        "- Professional Certifications",
        "    - CA: Chartered Accountancy pathway",
        "    - CS: Company Secretary certification",
        "    - UPSC: Civil Services exams",
      ],
    },
  ],
  glossaryTitle: "Glossary of Career Terms",
  glossaryDescription: "Quick reference for common abbreviations and terms used in Indian education and careers.",
  glossary: [
    { shortform: "S.S.C.", meaning: "School Secondary Certificate (10th standard)" },
    { shortform: "H.S.C.", meaning: "Higher Secondary Certificate (12th standard)" },
    { shortform: "ITI", meaning: "Industrial Training Institute" },
    { shortform: "JEE", meaning: "Joint Entrance Examination" },
    { shortform: "CET", meaning: "Common Entrance Test" },
    { shortform: "MBBS", meaning: "Bachelor of Medicine, Bachelor of Surgery" },
    { shortform: "BDS", meaning: "Bachelor of Dental Surgery" },
    { shortform: "B.Pharm", meaning: "Bachelor of Pharmacy" },
    { shortform: "B.Sc", meaning: "Bachelor of Science" },
    { shortform: "B.Com", meaning: "Bachelor of Commerce" },
    { shortform: "BBA", meaning: "Bachelor of Business Administration" },
    { shortform: "BMS", meaning: "Bachelor of Management Studies" },
    { shortform: "BCA", meaning: "Bachelor of Computer Applications" },
    { shortform: "B.A.", meaning: "Bachelor of Arts" },
    { shortform: "BSW", meaning: "Bachelor of Social Work" },
    { shortform: "M.Tech", meaning: "Master of Technology" },
    { shortform: "M.Sc", meaning: "Master of Science" },
    { shortform: "MBA", meaning: "Master of Business Administration" },
    { shortform: "MCA", meaning: "Master of Computer Applications" },
    { shortform: "PGDM", meaning: "Post Graduate Diploma in Management" },
    { shortform: "CA", meaning: "Chartered Accountant" },
    { shortform: "CS", meaning: "Company Secretary" },
    { shortform: "UPSC", meaning: "Union Public Service Commission" },
    { shortform: "AI", meaning: "Artificial Intelligence" },
    { shortform: "UI/UX", meaning: "User Interface / User Experience Design" },
  ],
};
